### ISSUE TITLE
are there more requirments to install ?

### ISSUE THREAD

**Issue by TheD3C4Y** [sensepost/dwn#2]
Hi, 
i have a fresh install of Ubuntu 18.04 LTS and have tried it 2 ways first with the offical docker install for Docker and Compose Python3 and pip3. I thought theres maybe a depency conflict so i startet from scratch only with python3 pip3 and python-docker via pip but i still get an traceback error if i run plain "dwn" or any one of the other commands

`root@host:/home/user# dwn
Traceback (most recent call last):
  File "/usr/local/bin/dwn", line 7, in <module>
    from dwn.cli.cli import cli
  File "/usr/local/lib/python3.6/dist-packages/dwn/cli/cli.py", line 4, in <module>
    from dwn.cli.commands.base import check, run, stop, show
  File "/usr/local/lib/python3.6/dist-packages/dwn/cli/commands/base.py", line 59
    if not (plan := loader.get_plan(name)):
                 ^
SyntaxError: invalid syntax`

it there anything else i have to install to use this toolkit ? 

my python version is 3.6.9

**Comment by leonjza** [comment]
Ooh. I realize now `dwn` actually requires python 3.8 for the walrus operator.

**Comment by TheD3C4Y** [comment]
thx got it working with python 3.8 ^^

**Comment by leonjza** [comment]
I'll keep this open so I can remember to fix the packaging. Thanks for the report!
